Added cpu and exhaustiveness specification to the directory preparation. Also general housekeeping.

diff --git a/3.prepare_docking_directories/prepare_AD_docking_directory b/3.prepare_docking_directories/prepare_AD_docking_directory
--- a/3.prepare_docking_directories/prepare_AD_docking_directory
+++ b/3.prepare_docking_directories/prepare_AD_docking_directory
@@ -28,6 +28,16 @@ while [ "${i}" -le "${Number_of_Replicas}" ] ; do
 			echo "INFO: Setting random seed for replica ${i} to ${AD2_Random_Seeds[${i}]}" >> ${Log_File}
 			echo "seed=${AD2_Random_Seeds[${i}]}" >> vcconfig
 		fi
+		if [ -z "${AD2_Docking_CPUS}" ] ; 
+			echo "INFO: Using default number of CPUs=8 and setting exhautiveness to match." >> ${Log_File}
+			echo "cpu=8" >> vcconfig
+			echo "exhaustiveness=8" >> vcconfig
+		else
+			echo "INFO: Using ${AD2_Docking_CPUS} CPUs and setting exhautiveness to match." >> ${Log_File}
+			echo "cpu=${AD2_Docking_CPUS}" >> vcconfig
+			echo "exhaustiveness=${AD2_Docking_CPUS}" >> vcconfig
+		fi
+	
 	else
 		echo "INFO: Found preexisting vcconfig for replica ${i}. Not clobbering." >> ${Log_File}
 	fi
@@ -48,11 +58,21 @@ while [ "${i}" -le "${Number_of_Replicas}" ] ; do
 	fi
 	#  copy the submission script if in batch mode. 
 	if [ ! -z "${AD2_Docking_Batch_Script}" ] ; then
+		if [ ! -e "${AD2_Docking_Batch_Script}" ] ; then
+			echo "ERROR: AD2_Docking_Batch_Script specified but not found. Exiting." >> ${Log_File}
+			echo "       The name given is: ${AD2_Docking_Batch_Script}" >> ${Log_File}
+			exit 1
+		fi
 		echo "INFO: copying the indicated script for batch processing." >> ${Log_File}
 		cp ../${AD2_Docking_Batch_Script} .
 	fi
 	#  copy the submission config if in batch mode. 
 	if [ ! -z "${AD2_Docking_Local_Script}" ] ; then
+		if [ ! -e "${AD2_Docking_Local_Script}" ] ; then
+			echo "ERROR: AD2_Docking_Local_Script specified but not found. Exiting." >> ${Log_File}
+			echo "       The name given is: ${AD2_Docking_Local_Script}" >> ${Log_File}
+			exit 1
+		fi
 		echo "INFO: copying the local config script for batch processing." >> ${Log_File}
 		cp ../${AD2_Docking_Local_Script} .
 	fi
